In [1]:
import numpy as np
# kalo blm ada di anaconda bisa download !pip install numpy

In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
type(a)

numpy.ndarray

In [ ]:
# Create blank list
my_list = []

In [ ]:
# beberapa function dari python
range()
print()
my_list.append()

In [8]:
# beberapa function dari numpy
np.arange(1,5,2) #sama kaya range kalo di python, ttp start stop step jg bentuknya
# start dari 1, stop di 4 (5 - 1), step 2
# np.array()
#np.zeros() #bikin isi nya 0
#np.ones(5) # bikin semua angka 1
# np. empty (15) #untuk buat missing value
np.append()

array([1, 3])

In [10]:
# create vector
b = np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [11]:
# contoh append
np.append(b,[7,8,9])

array([1, 2, 3, 4, 5, 7, 8, 9])

In [12]:
b # append tidak akan mengubah data asli (temporary)

array([1, 2, 3, 4, 5])

In [26]:
# cara merubah b permanen:
b = np.append(b,[7,8,9]) # dgn cara overwrite

In [27]:
b

array([1, 2, 3, 4, 5, 7, 8, 9, 6, 6, 6, 6, 7, 8, 9])

In [17]:
# oops we miss 6
#np.append(b,6, inplace=True) #parameter inplace hanya bisa di pandas

TypeError: append() got an unexpected keyword argument 'inplace'

In [24]:
b = np.append(b,6)
b

array([1, 2, 3, 4, 5, 7, 8, 9, 6, 6, 6, 6])

In [20]:
np.sort(b)

array([1, 2, 3, 4, 5, 6, 6, 7, 8, 9])

In [ ]:
# size untuk tau element
# shape untuk tau barisnya berapa, kolomnya berapa
#ndim untuk jumlah dimension 

In [28]:
b = np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [31]:
b = np.append(b,[7,8,9])
b

array([1, 2, 3, 4, 5, 7, 8, 9, 7, 8, 9])

In [33]:
b = np.append(b,6)
b

array([1, 2, 3, 4, 5, 7, 8, 9, 7, 8, 9, 6, 6])

In [35]:
b = np.sort(b)
b

array([1, 2, 3, 4, 5, 6, 6, 7, 7, 8, 8, 9, 9])

In [39]:
b.reshape(13,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [6],
       [7],
       [7],
       [8],
       [8],
       [9],
       [9]])

In [41]:
b.reshape(7,2)

ValueError: cannot reshape array of size 13 into shape (7,2)

In [42]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [45]:
z = np.array([[1,2,3,4],[5,6,7,8,],[10,11,12,13]])

Indexing and slicing

In [46]:
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [48]:
z[np.logical_and(z >=5, z < 8)] = 0

In [49]:
z

array([[ 1,  2,  3,  4],
       [ 0,  0,  0,  8],
       [10, 11, 12, 13]])

In [51]:
z [ (z >= 5) & (z < 8) ] =0

In [52]:
z

array([[ 1,  2,  3,  4],
       [ 0,  0,  0,  8],
       [10, 11, 12, 13]])

In [ ]:
# Perkalian vector ADA 2 METOD: `element wise` dan `dot product``

f = [1,2,3]
g = [4,5,6]
vect_f = np.array(f)
vect_g = np.array(g)
print('Hasil perkalian element wise')
print(vect_f * vect_g)
print('')

print('Hasil perkalian dot product')
print(vect_f.dot(vect_g)) # cara 1
print(vect_f@vect_g) # cara 2
print(np.dot(vect_f, vect_g)) # cara 3

# Studi Kasus

```
teks_1 = saya pergi ke rumah kakek saya
teks_2 = saya pergi ke rumah nenek saya
```

In [53]:
# unique words : [saya, pergi, ke, rumah, kakek, nenek]
t1 = [2,1,1,1,1,0]
t2 = [2,1,1,1,0,1]

vect_t1 = np.array(t1)
vect_t2 = np.array(t2)

cos_theta = (vect_t1@vect_t2) / (np.linalg.norm(vect_t1) * np.linalg.norm(vect_t2))
cos_theta

0.8749999999999998

In [ ]:
# perkalian vector (Matrix Multiplication) menggunakan @ jika shape matrix berbeda

A = [[1,2],
     [3,4],
     [5,6]]

B = [[1,2],
     [3,4]]     

matrix_A = np.array(A)
matrix_B = np.array(B)

print(matrix_A@matrix_B)

tes iseng dr kode.id

In [54]:
np.empty(6)

array([2., 1., 1., 1., 0., 1.])

In [57]:
np.arange(4)
np.arange(0,12,2) #start,stop,step

array([ 0,  2,  4,  6,  8, 10])

add, remove, sort

In [58]:
arr = np.array([1,2,3,4,5,6,7,8])

In [59]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [61]:
np.delete(arr, 6)

array([1, 2, 3, 4, 5, 6, 8])

In [62]:
arr = np.array([2,1,5,3,7,4,6,8])

In [63]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

shape and size

In [ ]:
ndarray.ndim() #memberitahu jumlah axis, atau dimensi dari array
ndarray.size() #membirtahu jumlah total element array
ndarray.shape() #menampilkan tuple integer yg menujukkan jumlah element yg disimpan di sepanjang setiap dimensi array
# jika misalnya ada larik 2D dengan 2 baris dan 3 kolom, maka bentuk larik adalah (2,3)

In [65]:
array_example = np.array([[[0,1,2,3],
                           [4,5,6,7]],
                           [[0,1,2,3],
                            [4,5,6,7]],
                            [[0,1,2,3],
                             [4,5,6,7]]])
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [66]:
array_example.ndim

3

In [67]:
array_example.size

24

In [68]:
array_example.shape #3 baris, 2 kolom, 4 elemen dlm 1 list

(3, 2, 4)

np.reshape (a, newshape, order)
newshape : bentuk baru yg kita inginkan (integer / tuple integer)
order: 'C' -- tead/write the elements using C'like index order,
       'F' -- read/wrtie elements using Fortran-like index order
       'A' -- read/wrtie elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order othereise

Convert 1D to 2D

In [69]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [70]:
a2 = a[np.newaxis]
print (a2.shape)
print (a2)

(1, 6)
[[1 2 3 4 5 6]]


also can insert row_vector = a[np.newaxis, :] and col_vector = a[:, np.newaxis]

In [71]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [72]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [73]:
c = np.expand_dims(a, axis = 0)
c.shape

(1, 6)

Indexing and slicing pt. 2

In [74]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [76]:
five_up = (a>=5)
print (a[five_up])
print (a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [77]:
divisible_by_2 = a[a%2==0]
print (divisible_by_2)

[ 2  4  6  8 10 12]


In [78]:
c = a [ (a > 2) & (a < 11)] #to print elements that satisfy 2 diff conditions
print (c)

[ 3  4  5  6  7  8  9 10]


creating array from existing data

In [ ]:
slicing indexing
np.vstack() #menumpuk array secara vertikal
np.hstack() # menumpuk array secara horizontal
np.hsplit()
.view() # membuat objek array baru yg terlihat sm dgn array asli (shallow copy)
.copy() # make a complete copy of the array and its data (deep copy)

In [79]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [81]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [86]:
a_1 = np.array ([[1,1],[2,2]])
a_2 = np.array ([[3,3],[4,4]])

In [87]:
a_1

array([[1, 1],
       [2, 2]])

In [88]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [89]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [90]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12],
                     [13,14,15,16,17,18,19,20,21,22,23,24]])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [92]:
np.hsplit(arrsplit,4)

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9],
        [19, 20, 21]]),
 array([[10, 11, 12],
        [22, 23, 24]])]

In [93]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [95]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Basic array operations (addition, substraction, multipilcation, division and more)

In [97]:
a = np.array([5,6,7,8])
a.sum()

26

In [99]:
b = np.array([[1,1], [2,2]])
b

array([[1, 1],
       [2, 2]])

In [100]:
b.sum(axis=0) #sum the rows

array([3, 3])

In [101]:
b.sum(axis=1) #sum the columns

array([2, 4])

In [102]:
data = np.array([1,2])
data

array([1, 2])

In [103]:
ones = np.ones(2)
ones

array([1., 1.])

In [104]:
data + ones

array([2., 3.])

In [105]:
data * data

array([1, 4])

In [106]:
data / data

array([1., 1.])

more array operations

In [ ]:
data.max()
data.min()
data.sum()
mean # mencari rata2
prod # mencari hasil perkalian elemen
std  # mencari standard deviation

creating matrices

In [108]:
# np.ones(())
# np.zeros(()))
np.random.random((3,2))

array([[0.88716956, 0.92680299],
       [0.26281609, 0.52092104],
       [0.80251118, 0.64139007]])

matrix arithmetic & dot product gitu pkknya 

matrix indexing

In [110]:
data = np.array([[1,2], [3,4], [5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [111]:
print (data[0])
print (data[1])
print (data[2])
print (data[0,1])
print (data[1:3])
print (data[0:2,1])

[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


transposing and reshaping

In [112]:
(data.T)

array([[1, 3, 5],
       [2, 4, 6]])

In [113]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [114]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [115]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [116]:
arr = np.arange(6).reshape((2,3)) 
# mebalikkan atau mengubah axes array sesuai dgn nilai yg kt tentukan
print(arr)

[[0 1 2]
 [3 4 5]]


n-dimensional array

In [117]:
ndarr = np.array([[1,2], [3,4], [5,6], [7,8]])
print(ndarr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [118]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


flatten n-dimensional array

In [119]:
arrflat = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])
print(arrflat) #referensi ke array induk

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [120]:
arrflat.flatten() #flatten into 1D array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

working with math formulas


In [121]:
error = (1/n) * np.sum(np.square(observed - prediction))

NameError: name 'n' is not defined

### TipsPy Notes on Numpy Vector

In [122]:
a = np.random.rand(5)
print (a)

[0.94587065 0.76864264 0.60291584 0.00450233 0.69604229]


In [123]:
a.shape # rank 1 array

(5,)

In [124]:
print(a.T)

[0.94587065 0.76864264 0.60291584 0.00450233 0.69604229]


In [125]:
print(np.dot(a, a.T))

2.333485447089023


tips untuk membuat array = selalu masukkan 2 argumen ketika akan membuat column ataupun row vector

In [127]:
a = np.random.rand(5,1) #column vector
print(a)

[[0.54133992]
 [0.52154274]
 [0.50827448]
 [0.06307429]
 [0.3337    ]]


In [128]:
print(a.T)

[[0.54133992 0.52154274 0.50827448 0.06307429 0.3337    ]]


In [129]:
print(np.dot(a, a.T))

[[0.29304891 0.28233191 0.27514927 0.03414463 0.18064513]
 [0.28233191 0.27200683 0.26508687 0.03289594 0.17403881]
 [0.27514927 0.26508687 0.25834295 0.03205905 0.1696112 ]
 [0.03414463 0.03289594 0.03205905 0.00397837 0.02104789]
 [0.18064513 0.17403881 0.1696112  0.02104789 0.11135569]]


In [130]:
a = np.random.rand(1,5) #row vector
a

array([[0.99597407, 0.86957046, 0.45057399, 0.26552789, 0.65913292]])

dont use rank 1 array; always use 1 by n matrices or n by 1 matrices instead. (column or row vectors)